apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  labels:
    app: mysql-config-map
data:
  MYSQL_DB_HOST: mysql
  #base de dato Estudiantes
  MYSQL_DB_ESTUADIANTES: estudiante
  #base de dato Cuotas
  MYSQL_DB_CUOTAS: cuota
  #base de dato Subir Notas
  MYSQL_DB_NOTAS: subir_notas